/**
 * Types
 */

const TYPES = {
  SET_LOADING: "FOLLOWERS/SET_LOADING",
  GET_FOLLOWERS_LIST: "FOLLOWERS/GET_FOLLOWERS_LIST",
  SET_FOLLOWERS_LIST: "FOLLOWERS/SET_FOLLOWERS_LIST",
  TOGGLE_SORT: "FOLLOWERS/TOGGLE_SORT",
  SET_ERROR: "FOLLOWERS/SET_ERROR",
  SET_SORTED_FOLLOWERS: "FOLLOWERS/SET_SORTED_FOLLOWERS",
};

export default TYPES;
