/**
 * Types
 */

const TYPES = {
  SET_LOADING: "AUTHENTICATE/SET_LOADING",
  SET_ERROR: "AUTHENTICATE/SET_ERROR",
  GET_REQUEST_TOKEN: "AUTHENTICATE/GET_REQUEST_TOKEN",
  SET_REQUEST_TOKEN: "AUTHENTICATE/SET_REQUEST_TOKEN",
  GET_ACCESS_TOKEN: "AUTHENTICATE/GET_ACCESS_TOKEN",
  SET_ACCESS_TOKEN: "AUTHENTICATE/SET_ACEESS_TOKEN",
};

export default TYPES;
